language: node_js
node_js:
  - '4.5.0'

sudo: false

install:
  - script/setup
  - gem install scss_lint --no-ri --version '=0.41.0'

script:
  - npm run-script travis_script

after_success:
  - npm run-script travis_after_success
